// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout"; // 1. 匯入新的 ClientLayout

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oking Inventory System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant">
      <body className={inter.className}>
        {/* 2. 直接使用 ClientLayout 來包裹 children */}
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
